name: Ubuntu (tmate)

on:
  workflow_dispatch:

jobs:
  Instance:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Run Start Script
      run: |
        wget https://github.com/cdr/code-server/releases/download/v3.9.3/code-server-3.9.3-linux-amd64.tar.gz
        tar xf code-server-3.9.3-linux-amd64.tar.gz
        cd code-server-3.9.3-linux-amd64
        export PASSWORD="${{ secrets.P }}"
        nohup ./code-server --port 8080 --host 0.0.0.0 --auth password &
        wget https://github.com/open-dingtalk/pierced/raw/master/linux/ding.cfg
        wget https://github.com/open-dingtalk/pierced/raw/master/linux/ding
        sudo chmod 777 ding
        ./ding -config=./ding.cfg -subdomain=${{ secrets.D }} 8080
